---
name: CI

on:
  push:
    tags: ["release/v*"]
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  tests:
    name: "Tests on Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        # I can't get the dbus, screensaver, and X11 infrastructure
        # in place to be able to test on Ubuntu in CI. Test locally!
        os: ["macos-latest", "windows-latest", "ubuntu-latest"]  
    runs-on: ${{ matrix.os }}
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install package under test
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[test]"
      - name: Run tests
        if: ${{ matrix.os!='ubuntu-latest' }}
        run: |
          python -m pytest tests/

  package:
    name: "Build Package Distributions"
    needs: tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.10"
      - name: "Build distribution"
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build
      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/release/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
